parameters:
    models: VAE-CF
    corruption: [0.3]
    rank: [50, 100, 200]
    topK: [5, 10, 15, 20, 50]
    iter: 300
    lambda: [0.00001, 0.0001, 0.001, 0.01, 0.1]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
